version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - mynetwork
    ports:
      - "8000:8000"
    environment:
      - EDEN_API_KEY=${EDEN_API_KEY}
      - GITHUB_API_TOKEN=${GITHUB_API_TOKEN}
      - LOG_FILE=/CodeReviewAI/logs/log.log
    volumes:
      - .:/CodeReviewAI
    command: ["bash", "/CodeReviewAI/run_fastapi.sh"]

  redis:
    image: redis:latest
    container_name: redis
    networks:
      - mynetwork
    ports:
      - 6379:6379
    volumes:
      - redis_data:/data

networks:
  mynetwork:
    driver: bridge

volumes:
  redis_data:
